export const FETCH_ARTICLE = "FETCH_ARTICLE";
export const FETCH_ARTICLE_SUCCESS = "FETCH_ARTICLE_SUCCESS";
export const FETCH_ARTICLE_FAILURE = "FETCH_ARTICLE_FAILURE";

export const FETCH_ARTICLES = "FETCH_ARTICLES";
export const FETCH_ARTICLES_SUCCESS = "FETCH_ARTICLES_SUCCESS";
export const FETCH_ARTICLES_FAILURE = "FETCH_ARTICLES_FAILURE";

export const FETCH_USER_ARTICLES = "FETCH_USER_ARTICLES";
export const FETCH_USER_ARTICLES_SUCCESS = "FETCH_USER_ARTICLES_SUCCESS";
export const FETCH_USER_ARTICLES_FAILURE = "FETCH_USER_ARTICLES_FAILURE";

export const FETCH_MORE_ARTICLES = "FETCH_MORE_ARTICLES";
export const FETCH_MORE_ARTICLES_SUCCESS = "FETCH_MORE_ARTICLES_SUCCESS";
export const FETCH_MORE_ARTICLES_FAILURE = "FETCH_MORE_ARTICLES_FAILURE";

export const FETCH_MORE_USER_ARTICLES = "FETCH_MORE_USER_ARTICLES";
export const FETCH_MORE_USER_ARTICLES_SUCCESS = "FETCH_MORE_USER_ARTICLES_SUCCESS";
export const FETCH_MORE_USER_ARTICLES_FAILURE = "FETCH_MORE_USER_ARTICLES_FAILURE";

export const UPDATE_ARTICLE = "UPDATE_ARTICLE";
export const UPDATE_ARTICLE_SUCCESS = "UPDATE_ARTICLE_SUCCESS";
export const UPDATE_ARTICLE_FAILURE = "UPDATE_ARTICLE_FAILURE";

export const CREATE_ARTICLE = "CREATE_ARTICLE";
export const CREATE_ARTICLE_SUCCESS = "CREATE_ARTICLE_SUCCESS";
export const CREATE_ARTICLE_FAILURE = "CREATE_ARTICLE_FAILURE";

export const DELETE_ARTICLE = "DELETE_ARTICLE";
export const DELETE_ARTICLE_SUCCESS = "DELETE_ARTICLE_SUCCESS";
export const DELETE_ARTICLE_FAILURE = "DELETE_ARTICLE_FAILURE";
