export const userConstants = {
	LOGIN_REQUEST: "LOGIN_REQUEST",
	LOGIN_SUCCESS: "LOGIN_SUCCESS",
	LOGIN_FAILURE: "LOGIN_FAILURE",

	// LOGOUT_REQUEST: "LOGOUT_REQUEST",
	LOGOUT_SUCCESS: "LOGOUT_SUCCESS",
	// LOGOUT_FAILURE: "LOGOUT_FAILURE",

	GET_ALL_REQUEST: "GET_ALL_REQUEST",
	GET_ALL_SUCCESS: "GET_ALL_SUCCESS",
	GET_ALL_FAILURE: "GET_ALL_FAILURE",

	GET_ONE_REQUEST: "GET_ONE_REQUEST",
	GET_ONE_SUCCESS: "GET_ONE_SUCCESS",
	GET_ONE_FAILURE: "GET_ONE_FAILURE"
};
