export const userConstants = {
	GET_ALL_REQUEST: "GET_ALL_REQUEST",
	GET_ALL_SUCCESS: "GET_ALL_SUCCESS",
	GET_ALL_FAILURE: "GET_ALL_FAILURE",

	GET_ONE_REQUEST: "GET_ONE_REQUEST",
	GET_ONE_SUCCESS: "GET_ONE_SUCCESS",
	GET_ONE_FAILURE: "GET_ONE_FAILURE",

	FOLLOW_REQUEST: "FOLLOW_REQUEST",
	FOLLOW_SUCCESS: "FOLLOW_SUCCESS",
	FOLLOW_FAILURE: "FOLLOW_FAILURE",

	UNFOLLOW_REQUEST: "UNFOLLOW_REQUEST",
	UNFOLLOW_SUCCESS: "UNFOLLOW_SUCCESS",
	UNFOLLOW_FAILURE: "UNFOLLOW_FAILURE"
};
